version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - pet-bot-network

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
      - FASTAPI_URL=http://fastapi:8000
    depends_on:
      - fastapi
    networks:
      - pet-bot-network

networks:
  pet-bot-network:
    driver: bridge
